 <div id="fbook"><a name="fb_share" type="button" href="http://www.facebook.com/sharer.php">Share</a><script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script><br /><br />
             <a href="http://twitter.com/CeratoBoutique"><img src="/images/twitterbutton-0103.png" title="Twitter" width="92" height="31" /></a><br /> 

<!-- <a href="documents/12Days_General_Creative.pdf"><img src="images/Promo_Button_1215.png" alt="Promo"></a> -->

                </div>