<div class="sidecss">

<ul>
        
        <li><a href="reports.php" title="Reports">Reporting</a></li>
        <li><a href="rank.php" title="Rank">Rank</a></li>
        </ul>

</div>
<br />

<!--
If you want a drop down, use the following code as a nested ul

	<li><a class="hide" href="../menu/hover_click.html" title="Hover/click with no active/focus borders">HOVER/CLICK &gt;</a>
		<ul>
			<li><a href="../menu/form.html" title="Styling forms">styled form</a></li>
			<li><a href="../menu/nodots.html" title="Removing active/focus borders">active focus</a></li>
			<li><a href="../menu/hover_click.html" title="Hover/click with no active/focus borders">hover/click</a></li>
		</ul>
        </li>
-->