<div class="sidecss">

<ul>
        
        <li><a href="dresses.php" title="Dresses">Dresses</a></li>
        <li><a href="tops.php" title="Tops">Tops</a></li>
	<li><a href="bottoms.php" title="Bottoms">Bottoms</a></li>
	<li><a href="accessories.php" title="Jewelry &amp; Handbags">Accessories</a>
        </ul>

</div>
<br />

<!--
If you want a drop down, use the following code as a nested ul

	<li><a class="hide" href="../menu/hover_click.html" title="Hover/click with no active/focus borders">HOVER/CLICK &gt;</a>
		<ul>
			<li><a href="../menu/form.html" title="Styling forms">styled form</a></li>
			<li><a href="../menu/nodots.html" title="Removing active/focus borders">active focus</a></li>
			<li><a href="../menu/hover_click.html" title="Hover/click with no active/focus borders">hover/click</a></li>
		</ul>
        </li>
-->