<div class="topmenu">

<ul>
        <li><a href="story.php" title="About Cerato Boutique">Our Story</a></li>
	<li><a href="designers.php" title="Featured Cerato Designers">Our Designers</a></li>
        <li><a class="hide" href="contact.php" title="Store Information">Store Info</a>
		<ul>
         <li><a class="noborder" href="contact.php" title="Contact Us">Contact Us</a></li>			
         <li><a class="noborder" href="form.php" title="Join Our Mailing List">Join Our Mailing List</a></li>
	        </ul>
        </li>
	<li><a href="press.php" title="Press">Press</a></li>
        <li><a href="news.php" title="News &amp; Events">News/Events</a></li>
        <li><a href="http://www.taigan.com/cerato
" title="Shop">Shop</a></li>
</ul>

</div>


<!--
If you want a drop down, use the following code as a nested ul

	<li><a class="hide" href="../menu/hover_click.html" title="Hover/click with no active/focus borders">HOVER/CLICK &gt;</a>
		<ul>
			<li><a href="../menu/form.html" title="Styling forms">styled form</a></li>
			<li><a href="../menu/nodots.html" title="Removing active/focus borders">active focus</a></li>
			<li><a href="../menu/hover_click.html" title="Hover/click with no active/focus borders">hover/click</a></li>
		</ul>
        </li>
-->